// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComAddress: typeof import('./src/components/com-address/com-address.vue')['default']
    Content: typeof import('./src/components/content/index.vue')['default']
    GoodsBox: typeof import('./src/components/goodsBox.vue')['default']
    GoodSort: typeof import('./src/components/goodSort/goodSort.vue')['default']
    Item: typeof import('./src/components/goodSort/item.vue')['default']
    NutAddress: typeof import('@nutui/nutui-taro')['Address']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBadge: typeof import('@nutui/nutui-taro')['Badge']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCategoryPane: typeof import('@nutui/nutui-taro')['CategoryPane']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutComment: typeof import('@nutui/nutui-taro')['Comment']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutImage: typeof import('@nutui/nutui-taro')['Image']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSku: typeof import('@nutui/nutui-taro')['Sku']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    Search: typeof import('./src/components/search/search.vue')['default']
    Swiper: typeof import('./src/components/swiper.vue')['default']
    TabCompoents: typeof import('./src/components/tabs/tabCompoents.vue')['default']
  }
}
